manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: tklzg
      url-base: https://github.com/tklzg
  projects:
    - name: zmk
      import: app/west.yml
      #remote: zmkfirmware
      #revision: main
      remote: tklzg
      revision: encoder
  self:
    path: config
