manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: encoder-feature
      url-base: https://github.com/stephen
  projects:
    - name: zmk
      import: app/west.yml
      #remote: zmkfirmware
      #revision: main
      remote: encoder-feature
      revision: split-encoder
  self:
    path: config